const ACTION_TYPE = {
    //  INCREMENT
    INCREMENT: 'INCREMENT',
    INCREMENT_REQUEST: 'INCREMENT_REQUEST',
    INCREMENT_REQUEST_SUCCESS: 'INCREMENT_REQUEST_SUCCESS',
    INCREMENT_REQUEST_ERROR: 'INCREMENT_REQUEST_ERROR',
    INCREMENT_MIDDLEWARE: 'INCREMENT_MIDDLEWARE',
    //  DECREMENT
    DECREMENT: 'DECREMENT',
    DECREMENT_REQUEST: 'DECREMENT_REQUEST',
    DECREMENT_REQUEST_SUCCESS: 'DECREMENT_REQUEST_SUCCESS',
    DECREMENT_REQUEST_ERROR: 'DECREMENT_REQUEST_ERROR',
    DECREMENT_MIDDLEWARE: 'DECREMENT_MIDDLEWARE',
    //  SET_STEP
    SET_STEP: 'SET_STEP',
    SET_STEP_REQUEST: 'SET_STEP_REQUEST',
    SET_STEP_REQUEST_SUCCESS: 'SET_STEP_REQUEST_SUCCESS',
    SET_STEP_REQUEST_ERROR: 'SET_STEP_REQUEST_ERROR',
    //  GET_STATE
    GET_STATE: 'GET_STATE',
    GET_STATE_REQUEST: 'GET_STATE_REQUEST',
    GET_STATE_REQUEST_SUCCESS: 'GET_STATE_REQUEST_SUCCESS',
    GET_STATE_REQUEST_ERROR: 'GET_STATE_REQUEST_ERROR',
};

export default ACTION_TYPE;
