const ACTION_TYPE = {
    SET_COUNTER_STATE_REQUEST: 'SET_COUNTER_STATE_REQUEST',
    SET_COUNTER_STATE_REQUEST_SUCCESS: 'SET_COUNTER_STATE_REQUEST_SUCCESS',
    SET_COUNTER_STATE_REQUEST_ERROR: 'SET_COUNTER_STATE_REQUEST_ERROR',
    //  INCREMENT
    INCREMENT: 'INCREMENT',
    //  DECREMENT
    DECREMENT: 'DECREMENT',
    //  SET_STEP
    SET_STEP: 'SET_STEP',
    //  GET_STATE
    GET_STATE: 'GET_STATE',
    GET_STATE_REQUEST: 'GET_STATE_REQUEST',
    GET_STATE_REQUEST_SUCCESS: 'GET_STATE_REQUEST_SUCCESS',
    GET_STATE_REQUEST_ERROR: 'GET_STATE_REQUEST_ERROR',
};

export default ACTION_TYPE;
